version: "3.7"
services:
  app:
    build:
      args:
        user: 'KTN6'
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: paksatpam
    container_name: paksatpam-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - paksatpam

  nginx:
    image: nginx:alpine
    container_name: paksatpam-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - paksatpam

networks:
  paksatpam:
    driver: bridge
